version: '3.9'
services:
  cargodb:
    container_name: 'cargodb'
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=DevCargo'
      - 'MYSQL_PASSWORD=secret'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=myuser'
    ports:
      - '3306:3306'
  spring:
    container_name: 'cargoapp'
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8080:8080'
    expose:
      - '8000'
    environment:
      - 'SPRING_PROFILES_ACTIVE=production'
    depends_on:
      - cargodb
